#!/usr/bin/env python3
"""Build 50-sources/sources.md: every URL cited in frontmatter `sources:` lists, what entries cite it,
and the parenthetical description authors attached. Run after build_index.py.

Usage: python3 jev/scripts/build_sources.py [jev-root]
"""
import json
import os
import re
import sys
from collections import defaultdict
from urllib.parse import urlparse

URL_RE = re.compile(r"(https?://[^\s)\]>\"'`]+)")


def main(root):
    idx = json.load(open(os.path.join(root, "index.json"), encoding="utf-8"))
    by_url = defaultdict(lambda: {"ids": set(), "notes": set()})
    for e in idx["entries"]:
        for s in e.get("sources") or []:
            m = URL_RE.search(s)
            if not m:
                continue
            u = m.group(1).rstrip(".,;:")
            note = s[m.end():].strip().strip("()").strip()
            by_url[u]["ids"].add(e["id"])
            if note:
                by_url[u]["notes"].add(note[:160])
    # url-check status if available
    status = {}
    uc = os.path.join(root, "50-sources", "url-check.md")
    if os.path.exists(uc):
        for line in open(uc, encoding="utf-8"):
            m = re.match(r"- (OK |BAD) `([^`]+)` (\S+)", line)
            if m:
                status[m.group(3)] = (m.group(1).strip(), m.group(2))
    groups = defaultdict(list)
    for u in by_url:
        host = urlparse(u).netloc.replace("www.", "")
        if host.endswith("typesafe.ai"):
            g = "TypeSafe (first-party)"
        elif "github.com" in host:
            g = "GitHub repositories and issues (community and independent)"
        elif host in {"news.ycombinator.com", "hn.algolia.com"}:
            g = "Hacker News"
        elif any(k in host for k in ("arxiv", "doi.org", "aclanthology", "openreview")):
            g = "Papers"
        elif any(k in host for k in ("platform.claude.com", "docs.anthropic", "openai.com", "ai.google.dev", "cohere", "huggingface", "pypi.org", "npmjs.com")):
            g = "Provider documentation, pricing, and package registries"
        else:
            g = "Press, blogs, and analyses"
        groups[g].append(u)
    order = ["TypeSafe (first-party)", "GitHub repositories and issues (community and independent)", "Papers",
             "Provider documentation, pricing, and package registries", "Hacker News", "Press, blogs, and analyses"]
    out = ["---", "id: sources-index", "title: Every source cited in corpus frontmatter, grouped by provenance",
           "last_verified: 2026-09-20", "jev_version: jev-1.13.0", "---", "",
           "# Sources",
           "",
           f"{len(by_url)} distinct URLs cited in entry frontmatter across {len(idx['entries'])} entries. "
           "Generated by `scripts/build_sources.py`; liveness from `url-check.md` where available "
           "(405 on the POST-only API endpoint is expected). Body-text citations that are not in frontmatter "
           "are not listed here; `check_sources.py` covers those.", ""]
    for g in order:
        urls = sorted(groups.get(g, []))
        if not urls:
            continue
        out += [f"## {g} ({len(urls)})", ""]
        for u in urls:
            st = status.get(u)
            mark = f" `{st[0]} {st[1]}`" if st else ""
            notes = "; ".join(sorted(by_url[u]["notes"]))[:400]
            ids = sorted(by_url[u]["ids"])
            shown = ", ".join(ids[:6]) + (f", +{len(ids) - 6} more" if len(ids) > 6 else "")
            out.append(f"- {u}{mark}")
            if notes:
                out.append(f"  - supports: {notes}")
            out.append(f"  - cited by: {shown}")
        out.append("")
    path = os.path.join(root, "50-sources", "sources.md")
    open(path, "w", encoding="utf-8").write("\n".join(out))
    print(f"written {path}: {len(by_url)} URLs in {len(groups)} groups")


if __name__ == "__main__":
    main(os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..")))
